# Numpy  

In [1]:
import numpy as np
import random

In [4]:
a = np.arange(8)
a

array([0, 1, 2, 3, 4, 5, 6, 7])

In [5]:
c1 = np.logspace(3.0, 4.0, num=4)
print(c1)


[ 1000.          2154.43469003  4641.58883361 10000.        ]


In [4]:
print ('Org Array',a)
print (a[5:8])

Org Array [0 1 2 3 4 5 6 7]
[5 6 7]


In [8]:
x1, y1 = np.meshgrid(np.arange(1, 11, 2), np.arange(-12, -3, 3))
print(x1)


[[1 3 5 7 9]
 [1 3 5 7 9]
 [1 3 5 7 9]]


In [13]:
r = random.randint(1,8)
r

6

In [14]:
e = np.array([(1,2,3),(4,5,6),(7,8,9)])
print(e)
print(e[2])


[[1 2 3]
 [4 5 6]
 [7 8 9]]
[7 8 9]


In [26]:
#**Before comma row values and after comma column values**

#all column from selected row
print(e[2:])
#all rows from selected column
print(e[:1])

[[7 8 9]]


# Array Slicing

In [44]:
# Array Slicing -- Sub array
# x[start:stop:step]
x = np.arange(10)
print(x)
print('First 5 elements', x[:5])
print('Last from 5', x[5:])
print(x[2:10:2])
# indexing from end of the array
print(x[-1])
print("From end",x[-5:-1])
# Reversing
print("Reverse",x[::-1])
# Every other element
print("Every other element", x[::2])

[0 1 2 3 4 5 6 7 8 9]
First 5 elements [0 1 2 3 4]
Last from 5 [5 6 7 8 9]
[2 4 6 8]
9
From end [5 6 7 8]
Reverse [9 8 7 6 5 4 3 2 1 0]
Every other element [0 2 4 6 8]


In [47]:
# Multi Dimensional Subarray
x2  = np.array([[1,2,5,6],[1,4,2,6],[1,8,3,7]])
print(x2)
# 2nd row 3rd column
print("2nd row 3rd column\n", x2[:2, :3])
# all row, every other column
print("all row, every other column\n", x2[:3, ::2])

[[1 2 5 6]
 [1 4 2 6]
 [1 8 3 7]]
2nd row 3rd column
 [[1 2 5]
 [1 4 2]]
all row, every other column
 [[1 5]
 [1 2]
 [1 3]]


In [9]:
# Creating copies of array
a = np.arange(20).reshape(4,5)
print("Org Array",a)
a[0,0] = 99
print(a)
print(a)
x2_sub_copy = a[:2, :2].copy()
print(x2_sub_copy)

Org Array [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
[[99  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
[[99  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
[[99  1]
 [ 5  6]]


# Concatenation

In [18]:
# Concatenation
x = np.array([1,2,3])
y = np.array([3,2,1])
print(np.concatenate([x,y]))
z = [99,21,43]
c = [5,2,5]
print(np.concatenate([z,x,y,c]))
# concatenate column wise
grid1 = np.array([[1,2,4],[5,2,5]])
grid2 = np.array([[4,1,7],[3,2,7]])
print(np.concatenate([grid1, grid2], axis=1))
print(np.concatenate([grid1, grid2], axis=0)) #Row wise

[1 2 3 3 2 1]
[99 21 43  1  2  3  3  2  1  5  2  5]
[[1 2 4 4 1 7]
 [5 2 5 3 2 7]]
[[1 2 4]
 [5 2 5]
 [4 1 7]
 [3 2 7]]


In [26]:
# np.vstack
# np.hstack
# when you want concatenation in mixed dimension
grid1 = np.array([1,2,4])
grid2 = np.array([[4,1,7],[3,2,7]])
grid3 = np.array([[4],[3]])
vstack = np.vstack([grid1,grid2])
print(vstack)
hstack = np.hstack([grid2, grid3])
print(hstack)

[[1 2 4]
 [4 1 7]
 [3 2 7]]
[[4 1 7 4]
 [3 2 7 3]]


# Splitting of array

In [40]:
# np.split, np.hsplit, np.vsplit
x = np.arange(10)
print(x)
x1, x2, x3 = np.split(x, [3,5])
print(x1, x2, x3)
# Split array into multiple subarray
w  = np.arange(8.0)
print("\n",np.array_split(x,2))
grid = np.arange(16).reshape((4,4))
print("\n",grid)
upper, lower = np.vsplit(grid,[2])
print(upper)
print(lower)
left, right = np.hsplit(grid, [1])
print(left)
print(right)

[0 1 2 3 4 5 6 7 8 9]
[0 1 2] [3 4] [5 6 7 8 9]

 [array([0, 1, 2, 3, 4]), array([5, 6, 7, 8, 9])]

 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[0 1 2 3]
 [4 5 6 7]]
[[ 8  9 10 11]
 [12 13 14 15]]
[[ 0]
 [ 4]
 [ 8]
 [12]]
[[ 1  2  3]
 [ 5  6  7]
 [ 9 10 11]
 [13 14 15]]


In [55]:
# Computation on NUmpy Array:
# Universal function
x =10
print(-(0.5*x+1)**2)
print((0.5*x+1)**2)
x =[10,20,30]
print(-(np.multiply(x,0.5)+1)**2)
print((np.multiply(x,0.5)+1)**2)

-36.0
36.0
[ -36. -121. -256.]
[ 36. 121. 256.]


In [8]:
# Fahrenheit to Centigrate
fvalues = [34.12,12.6,34.12,0,123.3]
F = np.array(fvalues)
print("Values in farenheit\n",F)
print("Values in centigrate\n",(5/9*(F-32)))

Values in farenheit
 [ 34.12  12.6   34.12   0.   123.3 ]
Values in centigrate
 [  1.17777778 -10.77777778   1.17777778 -17.77777778  50.72222222]


# Multiplication

In [11]:

a = np.array([[0,1],[5,9]])
b = np.array([[3,5],[4,5]])
dotproduct = np.dot(a,b)
print("Dot product\n",dotproduct)
multiply = np.matmul(a,b,out=None)
print("Matrix multiplication\n", multiply)

Dot product
 [[ 4  5]
 [51 70]]
Matrix multiplication
 [[ 4  5]
 [51 70]]


# Broadcasting

In [12]:
x = np.arange(3)+5
print(x)

[5 6 7]


# Fancy Indexing
passing an array of indices to access multiply array elements at once.

In [26]:
rand = np.random.RandomState(42)
x = rand.randint(100,size=10)
print(x)
ind  = [3,7,4]
print(x[ind])

[51 92 14 71 60 20 82 86 74 74]
[71 86 60]


In [19]:
# ind  = np.array([[3,7],[4,5]])
# x[ind]
X = np.arange(12).reshape((3,4))
print(X)
row  = np.array([0,1,2])
col = np.array([2,1,3])
print("\n",X[row,col])

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

 [ 2  5 11]


# Functions
Sorting
Regression
Covariance
Correlation

In [28]:
#1D array
Z  = np.zeros(10)
Z[4] =10
print(Z)

[ 0.  0.  0.  0. 10.  0.  0.  0.  0.  0.]


In [33]:
#2D array of shape(5,2). Element between 10,20 and gap between elements must be equal
arr = np.arange(10,30)
ar1 = arr.reshape(5,4)
print(ar1)

[[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]
 [22 23 24 25]
 [26 27 28 29]]
