Head and tail function
First N rows and Last N rows

In [2]:
import pandas as pd
import numpy as np

In [6]:
data = pd.read_csv("data.csv")
#print(data)

#print(data.head())
#print(data.tail())
data.head()

MODELYEAR   MAKE       MODEL VEHICLECLASS  ENGINESIZE  CYLINDERS  \
0       2014  ACURA         ILX      COMPACT         2.0          4   
1       2014  ACURA         ILX      COMPACT         2.4          4   
2       2014  ACURA  ILX HYBRID      COMPACT         1.5          4   
3       2014  ACURA     MDX 4WD  SUV - SMALL         3.5          6   
4       2014  ACURA     RDX AWD  SUV - SMALL         3.5          6   

  TRANSMISSION FUELTYPE  FUELCONSUMPTION_CITY  FUELCONSUMPTION_HWY  \
0          AS5        Z                   9.9                  6.7   
1           M6        Z                  11.2                  7.7   
2          AV7        Z                   6.0                  5.8   
3          AS6        Z                  12.7                  9.1   
4          AS6        Z                  12.1                  8.7   

   FUELCONSUMPTION_COMB  FUELCONSUMPTION_COMB_MPG  CO2EMISSIONS  
0                   8.5                        33           196  
1                   9.6                        29           221  
2                   5.9                        48           136  
3                  11.1                        25           255  
4                  10.6                        27           244

In [8]:
# describe()
#data.describe()
data.describe(include="all")

MODELYEAR  MAKE     MODEL VEHICLECLASS   ENGINESIZE    CYLINDERS  \
count      1067.0  1067      1067         1067  1067.000000  1067.000000   
unique        NaN    39       663           16          NaN          NaN   
top           NaN  FORD  F150 FFV     MID-SIZE          NaN          NaN   
freq          NaN    90         8          178          NaN          NaN   
mean       2014.0   NaN       NaN          NaN     3.346298     5.794752   
std           0.0   NaN       NaN          NaN     1.415895     1.797447   
min        2014.0   NaN       NaN          NaN     1.000000     3.000000   
25%        2014.0   NaN       NaN          NaN     2.000000     4.000000   
50%        2014.0   NaN       NaN          NaN     3.400000     6.000000   
75%        2014.0   NaN       NaN          NaN     4.300000     8.000000   
max        2014.0   NaN       NaN          NaN     8.400000    12.000000   

       TRANSMISSION FUELTYPE  FUELCONSUMPTION_CITY  FUELCONSUMPTION_HWY  \
count          1067     1067           1067.000000          1067.000000   
unique           22        4                   NaN                  NaN   
top              A6        X                   NaN                  NaN   
freq            222      514                   NaN                  NaN   
mean            NaN      NaN             13.296532             9.474602   
std             NaN      NaN              4.101253             2.794510   
min             NaN      NaN              4.600000             4.900000   
25%             NaN      NaN             10.250000             7.500000   
50%             NaN      NaN             12.600000             8.800000   
75%             NaN      NaN             15.550000            10.850000   
max             NaN      NaN             30.200000            20.500000   

        FUELCONSUMPTION_COMB  FUELCONSUMPTION_COMB_MPG  CO2EMISSIONS  
count            1067.000000               1067.000000   1067.000000  
unique                   NaN                       NaN           NaN  
top                      NaN                       NaN           NaN  
freq                     NaN                       NaN           NaN  
mean               11.580881                 26.441425    256.228679  
std                 3.485595                  7.468702     63.372304  
min                 4.700000                 11.000000    108.000000  
25%                 9.000000                 21.000000    207.000000  
50%                10.900000                 26.000000    251.000000  
75%                13.350000                 31.000000    294.000000  
max                25.800000                 60.000000    488.000000

In [9]:
d = {'Name':pd.Series(['Ayush','Aditya','Arun','Saket','Animesh']), 'Age':pd.Series([21,16,20,22,21]),
     'score1':[54,65,76,84,76], 'score2':[75,76,90,31,65]}
df = pd.DataFrame(d)
print(df)
df.head()


      Name  Age  score1  score2
0    Ayush   21      54      75
1   Aditya   16      65      76
2     Arun   20      76      90
3    Saket   22      84      31
4  Animesh   21      76      65


Name  Age  score1  score2
0    Ayush   21      54      75
1   Aditya   16      65      76
2     Arun   20      76      90
3    Saket   22      84      31
4  Animesh   21      76      65

In [10]:
print(df.mean())

Age       20.0
score1    71.0
score2    67.4
dtype: float64


In [11]:
#Row mean of the dataframe
print(df.mean(axis=1))

0    50.000000
1    52.333333
2    62.000000
3    45.666667
4    54.000000
dtype: float64


In [16]:
df.loc[:,'score1'].mean()


71.0

In [18]:
print(df.median())

Age       21.0
score1    76.0
score2    75.0
dtype: float64


In [20]:
df.loc[:,'score2'].median()

75.0

In [22]:
#Transpose
print(df.T)

            0       1     2      3        4
Name    Ayush  Aditya  Arun  Saket  Animesh
Age        21      16    20     22       21
score1     54      65    76     84       76
score2     75      76    90     31       65


In [24]:
print(df.Age)

0    21
1    16
2    20
3    22
4    21
Name: Age, dtype: int64


In [28]:
rng = np.random.RandomState(40)
ser = pd.Series(rng.randint(1,20,5))
print(ser)

0     7
1     8
2     6
3    19
4     2
dtype: int32


In [29]:
ar = np.random.randint(10, size=(3,5))
print(ar)

[[5 5 5 9 4]
 [1 3 9 1 8]
 [5 8 9 4 2]]


In [32]:
df = pd.DataFrame(rng.randint(0,10,(3,4)), columns= ['A','B','C','D'])
print(df)

   A  B  C  D
0  4  8  6  3
1  3  7  7  1
2  3  5  2  2


In [33]:
A = pd.DataFrame(rng.randint(0,20,(2,2)), columns=list('AB'))
print(A)

    A   B
0  15   3
1  12  14


In [38]:
print(np.exp(ser))
print()
print(np.sin(df*np.pi/4))
print()

A = pd.Series([2,4,5], index=[0,1,2])
B = pd.Series([1,3,4], index=[1,2,3])

print(A+B)

0    1.096633e+03
1    2.980958e+03
2    4.034288e+02
3    1.784823e+08
4    7.389056e+00
dtype: float64

              A             B         C         D
0  1.224647e-16 -2.449294e-16 -1.000000  0.707107
1  7.071068e-01 -7.071068e-01 -0.707107  0.707107
2  7.071068e-01 -7.071068e-01  1.000000  1.000000

0    NaN
1    5.0
2    8.0
3    NaN
dtype: float64


In [40]:
print(A.add(B, fill_value=0))

0    2.0
1    5.0
2    8.0
3    4.0
dtype: float64


# DataFrame.pop()
take input of a column from a dataframe and pop it directly

# Example
'Name':['Ayush','Aditya'], 'Examm':['Sem1','Sem2'], 'Subject':['Math','Python'], 'Score':[55,56]

In [15]:
d = {'Name':['Ayush','Aditya','Saket','Sanjiv'], 'Examm':['Sem1','Sem2','Sem2','Sem1'], 'Subject':['Math','Python','C++','Java'], 'Score':[55,56,65,77]}
df = pd.DataFrame(d)
print(df['Name'])
print()
print(df)
print()
print(df[['Name', 'Score']])

0     Ayush
1    Aditya
2     Saket
3    Sanjiv
Name: Name, dtype: object

     Name Examm Subject  Score
0   Ayush  Sem1    Math     55
1  Aditya  Sem2  Python     56
2   Saket  Sem2     C++     65
3  Sanjiv  Sem1    Java     77

     Name  Score
0   Ayush     55
1  Aditya     56
2   Saket     65
3  Sanjiv     77


In [18]:
print(df[df['Score']<56])
print()
print(df[(df['Score']<56)&(df['Score']>50)])

    Name Examm Subject  Score
0  Ayush  Sem1    Math     55

    Name Examm Subject  Score
0  Ayush  Sem1    Math     55


In [19]:
df['Score']>56

0    False
1    False
2     True
3     True
Name: Score, dtype: bool

# Indexing with .ix
ix[] isused to index a dataframe by bith name and position

In [20]:
print(df.ix[:,'Score'])

0    55
1    56
2    65
3    77
Name: Score, dtype: int64


C:\Users\ayush\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: DeprecationWarning: 
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/indexing.html#ix-indexer-is-deprecated
  """Entry point for launching an IPython kernel.


In [21]:
df.iloc[:2]

Name Examm Subject  Score
0   Ayush  Sem1    Math     55
1  Aditya  Sem2  Python     56

In [22]:
df.iloc[2:4]

Name Examm Subject  Score
2   Saket  Sem2     C++     65
3  Sanjiv  Sem1    Java     77

In [24]:
#Select first two column
df.iloc[:,:2]

Name Examm
0   Ayush  Sem1
1  Aditya  Sem2
2   Saket  Sem2
3  Sanjiv  Sem1

In [25]:
#select all rows starting from 2nd row
df.iloc[2:,]

Name Examm Subject  Score
2   Saket  Sem2     C++     65
3  Sanjiv  Sem1    Java     77

3 methods

In [26]:
df[:2]
df.head(2)
df.iloc[2:,]

Name Examm Subject  Score
2   Saket  Sem2     C++     65
3  Sanjiv  Sem1    Java     77

In [34]:
print(df.loc[[0,1,2,3],['Name','Subject','Score']])

     Name Subject  Score
0   Ayush    Math     55
1  Aditya  Python     56
2   Saket     C++     65
3  Sanjiv    Java     77


# Difference between loc and iloc
1. .loc[[list of row name],[list of col name]] is used to select or index rows and cols based on their name (name based indexing)
2. .iloc[row no range, col no range] is position based indexing